-- MySQL Script generated by MySQL Workbench
-- Sat Jan 14 21:52:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`platforme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`platforme` ;

CREATE TABLE IF NOT EXISTS `mydb`.`platforme` (
  `id_platforme` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `konzola` SMALLINT(1) NULL,
  PRIMARY KEY (`id_platforme`),
  UNIQUE INDEX `id_platforme_UNIQUE` (`id_platforme` ASC),
  UNIQUE INDEX `naziv_UNIQUE` (`naziv` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`igre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`igre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`igre` (
  `id_igre` INT NOT NULL AUTO_INCREMENT,
  `naslov` VARCHAR(45) NOT NULL,
  `datum_izlaska` DATE NOT NULL,
  `developer` VARCHAR(45) NULL,
  `fransiza` INT NULL,
  PRIMARY KEY (`id_igre`),
  INDEX `fk_igre_igre1_idx` (`fransiza` ASC),
  CONSTRAINT `fk_igre_igre1`
    FOREIGN KEY (`fransiza`)
    REFERENCES `mydb`.`igre` (`id_igre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zanrovi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`zanrovi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`zanrovi` (
  `id_žanrovi` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_žanrovi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tip_korisnika`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tip_korisnika` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tip_korisnika` (
  `id_tip_korisnika` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tip_korisnika`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`korisnici`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`korisnici` ;

CREATE TABLE IF NOT EXISTS `mydb`.`korisnici` (
  `id_korisnici` INT NOT NULL AUTO_INCREMENT,
  `korime` VARCHAR(45) NOT NULL,
  `tip_korisnika` INT NOT NULL,
  `broj_kartice` VARCHAR(16) NOT NULL,
  `lozinka` VARCHAR(20) NOT NULL,
  `email` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_korisnici`),
  INDEX `fk_korisnici_tip_korisnika1_idx` (`tip_korisnika` ASC),
  CONSTRAINT `fk_korisnici_tip_korisnika1`
    FOREIGN KEY (`tip_korisnika`)
    REFERENCES `mydb`.`tip_korisnika` (`id_tip_korisnika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`platforme_igre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`platforme_igre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`platforme_igre` (
  `id_platforme` INT NOT NULL,
  `id_igre` INT NOT NULL,
  `datum_dostupnosti` DATE NULL,
  PRIMARY KEY (`id_platforme`, `id_igre`),
  INDEX `fk_platforme_has_igre_igre1_idx` (`id_igre` ASC),
  INDEX `fk_platforme_has_igre_platforme_idx` (`id_platforme` ASC),
  CONSTRAINT `fk_platforme_has_igre_platforme`
    FOREIGN KEY (`id_platforme`)
    REFERENCES `mydb`.`platforme` (`id_platforme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_platforme_has_igre_igre1`
    FOREIGN KEY (`id_igre`)
    REFERENCES `mydb`.`igre` (`id_igre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zanrovi_igre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`zanrovi_igre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`zanrovi_igre` (
  `id_žanrovi` INT NOT NULL,
  `id_igre` INT NOT NULL,
  PRIMARY KEY (`id_žanrovi`, `id_igre`),
  INDEX `fk_žanrovi_has_igre_igre1_idx` (`id_igre` ASC),
  INDEX `fk_žanrovi_has_igre_žanrovi1_idx` (`id_žanrovi` ASC),
  CONSTRAINT `fk_žanrovi_has_igre_žanrovi1`
    FOREIGN KEY (`id_žanrovi`)
    REFERENCES `mydb`.`zanrovi` (`id_žanrovi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_žanrovi_has_igre_igre1`
    FOREIGN KEY (`id_igre`)
    REFERENCES `mydb`.`igre` (`id_igre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lista_zelja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lista_zelja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lista_zelja` (
  `id_igre` INT NOT NULL,
  `id_korisnici` INT NOT NULL,
  `vrijeme_dodavanja` DATETIME NOT NULL,
  `kupljena` SMALLINT(1) NULL,
  PRIMARY KEY (`id_igre`, `id_korisnici`),
  INDEX `fk_igre_has_korisnici_korisnici1_idx` (`id_korisnici` ASC),
  INDEX `fk_igre_has_korisnici_igre1_idx` (`id_igre` ASC),
  CONSTRAINT `fk_igre_has_korisnici_igre1`
    FOREIGN KEY (`id_igre`)
    REFERENCES `mydb`.`igre` (`id_igre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_igre_has_korisnici_korisnici1`
    FOREIGN KEY (`id_korisnici`)
    REFERENCES `mydb`.`korisnici` (`id_korisnici`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`katalog_igara`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`katalog_igara` ;

CREATE TABLE IF NOT EXISTS `mydb`.`katalog_igara` (
  `id_igre` INT NOT NULL,
  `id_korisnici` INT NOT NULL,
  `vrijeme_kupnje` DATETIME NOT NULL,
  PRIMARY KEY (`id_igre`, `id_korisnici`),
  INDEX `fk_igre_has_korisnici_korisnici2_idx` (`id_korisnici` ASC),
  INDEX `fk_igre_has_korisnici_igre2_idx` (`id_igre` ASC),
  CONSTRAINT `fk_igre_has_korisnici_igre2`
    FOREIGN KEY (`id_igre`)
    REFERENCES `mydb`.`igre` (`id_igre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_igre_has_korisnici_korisnici2`
    FOREIGN KEY (`id_korisnici`)
    REFERENCES `mydb`.`korisnici` (`id_korisnici`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prethodnice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`prethodnice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`prethodnice` (
  `id_igre` INT NOT NULL,
  `id_prethodnice` INT NOT NULL,
  PRIMARY KEY (`id_igre`, `id_prethodnice`),
  INDEX `id_prethodnice_fk_idx` (`id_prethodnice` ASC),
  CONSTRAINT `id_igre_fk`
    FOREIGN KEY (`id_igre`)
    REFERENCES `mydb`.`igre` (`id_igre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_prethodnice_fk`
    FOREIGN KEY (`id_prethodnice`)
    REFERENCES `mydb`.`igre` (`id_igre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
